### ISSUE TITLE
Parse .ips crash logs

### ISSUE THREAD

**Issue by yossizahn** [packagesdev/unexpectedly#5]
Hi,
Thanks for a great app!
Since I installed Monterey I am not seeing crash reports anymore in Unexpectedly.
I think the reason is that Apple seems to be creating them in a different format, .ips as opposed to .crash.

**Comment by packagesdev** [comment]
.ips support is a feature that is currently under development. As you have noticed, the part that includes being able to read .ips files and produces a text file is almost done.

**Comment by packagesdev** [comment]
.ips support now includes symbolication. I'm now checking various .ips files to check that the rendering and conversion are working fine.

**Comment by packagesdev** [comment]
Just in case, .ips support has been added to beta 3.

http://s.sudre.free.fr/Software/Unexpectedly/release_notes.html
