### ISSUE TITLE
Seems to have stopped working on macOS Ventura

### ISSUE THREAD

**Issue by nickkaczmarek** [packagesdev/unexpectedly#6]
I'm not sure if the app is requiring permissions for something or something else may be happening, but I can no longer view crash logs in Unexpectedly. Not sure where to go from here, but perhaps someone has some insight.

<img width="1449" alt="Screenshot 2023-01-06 at 13 47 20" src="https://user-images.githubusercontent.com/9044401/211088177-eaab2d35-967d-4b95-b7b6-705be44c104d.png">

**Comment by packagesdev** [comment]
This issue is fixed in the code on github.
